export { default as Aside } from "./Aside";
export { default as EventBox } from "./EventBox"
export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as LoginForm } from "./LoginForm";
export { default as Main } from "./Main";
export { default as NavBar } from "./NavBar";
export { default as Order } from "./Order";
export { default as RoomBox } from './RoomBox';
export { default as ServiceBox } from './ServiceBox';